version: '2'
services:

  apache:
    image: httpd:alpine
    ports:
     - "8000:80"
    volumes:
      - ./configuration/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    networks:
      - demo

  test-webapp:
    image: tutum/hello-world
    ports: 
      - "9080:80"
    networks:
      demo:
        aliases:
          - www.test.net

networks:
  demo:
    driver: bridge
